export const parcel_groups = [
  {
    sector: 0,
    parcels: [
      { id: 1, thumb: '/temp/temp-logo.jpg', x: 0, y: 0, ownerAddress: null, available: false, sector: 0 },
      { id: 2, thumb: null, image: '/temp/1.jpg', x: 3, y: 0, ownerAddress: null, available: false, sector: 0 },
      { id: 3, thumb: '/temp/ape2.png', x: 2.1, y: 2.2, ownerAddress: null, available: false, sector: 0 },
      { id: 4, thumb: null, image: '/temp/1.jpg', x: 0, y: 3.2, ownerAddress: null, available: false, sector: 0 },
      { id: 5, thumb: null, image: '/temp/2.jpg', x: -2.1, y: 2.2, ownerAddress: null, available: false, sector: 0 },
      { id: 6, thumb: null, image: '/temp/3.jpg', x: 2.1, y: -2.2, ownerAddress: null, available: false, sector: 0 },
      { id: 7, thumb: null, image: '/temp/4.jpg', x: 0, y: -3.2, ownerAddress: null, available: false, sector: 0 },
      {
        id: 8,
        thumb: null,
        image: '/temp/5.jpg',
        x: -2.1,
        y: -2.2,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      { id: 9, thumb: null, image: '/temp/6.jpg', x: -3, y: 0, ownerAddress: null, available: false, sector: 0 },
      { id: 10, thumb: null, image: '/temp/1.jpg', x: 4.2, y: 1.9, ownerAddress: null, available: false, sector: 0 },
      { id: 11, thumb: null, image: '/temp/2.jpg', x: 5.2, y: 0, ownerAddress: null, available: false, sector: 0 },
      { id: 12, thumb: null, image: '/temp/3.jpg', x: 3.2, y: 3.9, ownerAddress: null, available: false, sector: 0 },
      { id: 13, thumb: null, image: '/temp/4.jpg', x: 1.2, y: 4.8, ownerAddress: null, available: false, sector: 0 },
      {
        id: 14,
        thumb: null,
        image: '/temp/5.jpg',
        x: 4.2,
        y: -1.9,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      { id: 15, thumb: null, image: '/temp/6.jpg', x: -5.2, y: 0, ownerAddress: null, available: false, sector: 0 },
      {
        id: 16,
        thumb: null,
        image: '/temp/1.jpg',
        x: 3.2,
        y: -3.9,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      {
        id: 17,
        thumb: null,
        image: '/temp/2.jpg',
        x: 1.2,
        y: -4.8,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      {
        id: 18,
        thumb: null,
        image: '/temp/3.jpg',
        x: -4.2,
        y: -1.9,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      {
        id: 19,
        thumb: null,
        image: '/temp/4.jpg',
        x: -3.2,
        y: -3.9,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      {
        id: 20,
        thumb: null,
        image: '/temp/5.jpg',
        x: -1.2,
        y: -4.8,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      {
        id: 21,
        thumb: null,
        image: '/temp/6.jpg',
        x: -4.2,
        y: 1.9,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      {
        id: 22,
        thumb: null,
        image: '/temp/1.jpg',
        x: -3.2,
        y: 3.9,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
      {
        id: 23,
        thumb: null,
        image: '/temp/2.jpg',
        x: -1.2,
        y: 4.8,
        ownerAddress: null,
        available: false,
        sector: 0,
      },
    ],
  },
  {
    sector: 1,
    parcels: [
      { id: 24, thumb: null, x: 7.5, y: 5.5, ownerAddress: null, available: true, sector: 1 },
      { id: 25, thumb: null, x: 9.5, y: 5.5, ownerAddress: null, available: true, sector: 1 },
      { id: 26, thumb: null, x: 6.5, y: 7.2, ownerAddress: null, available: true, sector: 1 },
      { id: 27, thumb: null, x: 8.5, y: 7.2, ownerAddress: null, available: true, sector: 1 },
      { id: 28, thumb: null, x: 10.5, y: 7.2, ownerAddress: null, available: true, sector: 1 },
      { id: 29, thumb: null, x: 5.5, y: 8.9, ownerAddress: null, available: true, sector: 1 },
      { id: 30, thumb: null, x: 7.5, y: 8.9, ownerAddress: null, available: true, sector: 1 },
      { id: 31, thumb: null, x: 9.5, y: 8.9, ownerAddress: null, available: true, sector: 1 },
      { id: 32, thumb: null, x: 11.5, y: 8.9, ownerAddress: null, available: true, sector: 1 },
      { id: 33, thumb: null, x: 6.5, y: 10.6, ownerAddress: null, available: true, sector: 1 },
      { id: 34, thumb: null, x: 8.5, y: 10.6, ownerAddress: null, available: true, sector: 1 },
      { id: 35, thumb: null, x: 10.5, y: 10.6, ownerAddress: null, available: true, sector: 1 },
      { id: 36, thumb: null, x: 7.5, y: 12.3, ownerAddress: null, available: true, sector: 1 },
      { id: 37, thumb: null, x: 9.5, y: 12.3, ownerAddress: null, available: true, sector: 1 },
    ],
  },
  {
    sector: 2,
    parcels: [
      { id: 38, thumb: null, x: 7.5, y: -5.5, ownerAddress: null, available: true, sector: 2 },
      { id: 39, thumb: null, x: 9.5, y: -5.5, ownerAddress: null, available: true, sector: 2 },
      { id: 40, thumb: null, x: 6.5, y: -7.2, ownerAddress: null, available: true, sector: 2 },
      { id: 41, thumb: null, x: 8.5, y: -7.2, ownerAddress: null, available: true, sector: 2 },
      { id: 42, thumb: null, x: 10.5, y: -7.2, ownerAddress: null, available: true, sector: 2 },
      { id: 43, thumb: null, x: 5.5, y: -8.9, ownerAddress: null, available: true, sector: 2 },
      { id: 44, thumb: null, x: 7.5, y: -8.9, ownerAddress: null, available: true, sector: 2 },
      { id: 45, thumb: null, x: 9.5, y: -8.9, ownerAddress: null, available: true, sector: 2 },
      { id: 46, thumb: null, x: 11.5, y: -8.9, ownerAddress: null, available: true, sector: 2 },
      { id: 47, thumb: null, x: 6.5, y: -10.6, ownerAddress: null, available: true, sector: 2 },
      { id: 48, thumb: null, x: 8.5, y: -10.6, ownerAddress: null, available: true, sector: 2 },
      { id: 49, thumb: null, x: 10.5, y: -10.6, ownerAddress: null, available: true, sector: 2 },
      { id: 50, thumb: null, x: 7.5, y: -12.3, ownerAddress: null, available: true, sector: 2 },
      { id: 51, thumb: null, x: 9.5, y: -12.3, ownerAddress: null, available: true, sector: 2 },
    ],
  },
  {
    sector: 3,
    parcels: [
      { id: 52, thumb: null, x: -7.5, y: 5.5, ownerAddress: null, available: true, sector: 3 },
      { id: 53, thumb: null, x: -9.5, y: 5.5, ownerAddress: null, available: true, sector: 3 },
      { id: 54, thumb: null, x: -6.5, y: 7.2, ownerAddress: null, available: true, sector: 3 },
      { id: 55, thumb: null, x: -8.5, y: 7.2, ownerAddress: null, available: true, sector: 3 },
      { id: 56, thumb: null, x: -10.5, y: 7.2, ownerAddress: null, available: true, sector: 3 },
      { id: 57, thumb: null, x: -5.5, y: 8.9, ownerAddress: null, available: true, sector: 3 },
      { id: 58, thumb: null, x: -7.5, y: 8.9, ownerAddress: null, available: true, sector: 3 },
      { id: 59, thumb: null, x: -9.5, y: 8.9, ownerAddress: null, available: true, sector: 3 },
      { id: 60, thumb: null, x: -11.5, y: 8.9, ownerAddress: null, available: true, sector: 3 },
      { id: 61, thumb: null, x: -6.5, y: 10.6, ownerAddress: null, available: true, sector: 3 },
      { id: 62, thumb: null, x: -8.5, y: 10.6, ownerAddress: null, available: true, sector: 3 },
      { id: 63, thumb: null, x: -10.5, y: 10.6, ownerAddress: null, available: true, sector: 3 },
      { id: 64, thumb: null, x: -7.5, y: 12.3, ownerAddress: null, available: true, sector: 3 },
      { id: 65, thumb: null, x: -9.5, y: 12.3, ownerAddress: null, available: true, sector: 3 },
    ],
  },
  {
    sector: 4,
    parcels: [
      { id: 66, thumb: null, x: -7.5, y: -5.5, ownerAddress: null, available: true, sector: 4 },
      { id: 67, thumb: null, x: -9.5, y: -5.5, ownerAddress: null, available: true, sector: 4 },
      { id: 68, thumb: null, x: -6.5, y: -7.2, ownerAddress: null, available: true, sector: 4 },
      { id: 69, thumb: null, x: -8.5, y: -7.2, ownerAddress: null, available: true, sector: 4 },
      { id: 70, thumb: null, x: -10.5, y: -7.2, ownerAddress: null, available: true, sector: 4 },
      { id: 71, thumb: null, x: -5.5, y: -8.9, ownerAddress: null, available: true, sector: 4 },
      { id: 72, thumb: null, x: -7.5, y: -8.9, ownerAddress: null, available: true, sector: 4 },
      { id: 73, thumb: null, x: -9.5, y: -8.9, ownerAddress: null, available: true, sector: 4 },
      { id: 74, thumb: null, x: -11.5, y: -8.9, ownerAddress: null, available: true, sector: 4 },
      { id: 75, thumb: null, x: -6.5, y: -10.6, ownerAddress: null, available: true, sector: 4 },
      { id: 76, thumb: null, x: -8.5, y: -10.6, ownerAddress: null, available: true, sector: 4 },
      { id: 77, thumb: null, x: -10.5, y: -10.6, ownerAddress: null, available: true, sector: 4 },
      { id: 78, thumb: null, x: -7.5, y: -12.3, ownerAddress: null, available: true, sector: 4 },
      { id: 79, thumb: null, x: -9.5, y: -12.3, ownerAddress: null, available: true, sector: 4 },
    ],
  },
  {
    sector: 5,
    parcels: [
      { id: 80, thumb: null, x: -1, y: 11.5, ownerAddress: null, available: true, sector: 5 },
      { id: 81, thumb: null, x: 1, y: 11.5, ownerAddress: null, available: true, sector: 5 },
      { id: 82, thumb: null, x: -2, y: 13.2, ownerAddress: null, available: true, sector: 5 },
      { id: 83, thumb: null, x: 0, y: 13.2, ownerAddress: null, available: true, sector: 5 },
      { id: 84, thumb: null, x: 2, y: 13.2, ownerAddress: null, available: true, sector: 5 },
      { id: 85, thumb: null, x: -1, y: 14.9, ownerAddress: null, available: true, sector: 5 },
      { id: 86, thumb: null, x: -3, y: 14.9, ownerAddress: null, available: true, sector: 5 },
      { id: 87, thumb: null, x: 1, y: 14.9, ownerAddress: null, available: true, sector: 5 },
      { id: 88, thumb: null, x: 3, y: 14.9, ownerAddress: null, available: true, sector: 5 },
      { id: 89, thumb: null, x: -2, y: 16.6, ownerAddress: null, available: true, sector: 5 },
      { id: 90, thumb: null, x: 0, y: 16.6, ownerAddress: null, available: true, sector: 5 },
      { id: 91, thumb: null, x: 2, y: 16.6, ownerAddress: null, available: true, sector: 5 },
      { id: 92, thumb: null, x: -1, y: 18.3, ownerAddress: null, available: true, sector: 5 },
      { id: 93, thumb: null, x: 1, y: 18.3, ownerAddress: null, available: true, sector: 5 },
    ],
  },
  {
    sector: 6,
    parcels: [
      { id: 94, thumb: null, x: -1, y: -11.5, ownerAddress: null, available: true, sector: 6 },
      { id: 95, thumb: null, x: 1, y: -11.5, ownerAddress: null, available: true, sector: 6 },
      { id: 96, thumb: null, x: -2, y: -13.2, ownerAddress: null, available: true, sector: 6 },
      { id: 97, thumb: null, x: 0, y: -13.2, ownerAddress: null, available: true, sector: 6 },
      { id: 98, thumb: null, x: 2, y: -13.2, ownerAddress: null, available: true, sector: 6 },
      { id: 99, thumb: null, x: -1, y: -14.9, ownerAddress: null, available: true, sector: 6 },
      { id: 100, thumb: null, x: -3, y: -14.9, ownerAddress: null, available: true, sector: 6 },
      { id: 101, thumb: null, x: 1, y: -14.9, ownerAddress: null, available: true, sector: 6 },
      { id: 102, thumb: null, x: 3, y: -14.9, ownerAddress: null, available: true, sector: 6 },
      { id: 103, thumb: null, x: -2, y: -16.6, ownerAddress: null, available: true, sector: 6 },
      { id: 104, thumb: null, x: 0, y: -16.6, ownerAddress: null, available: true, sector: 6 },
      { id: 105, thumb: null, x: 2, y: -16.6, ownerAddress: null, available: true, sector: 6 },
      { id: 106, thumb: null, x: -1, y: -18.3, ownerAddress: null, available: true, sector: 6 },
      { id: 107, thumb: null, x: 1, y: -18.3, ownerAddress: null, available: true, sector: 6 },
    ],
  },
  {
    sector: 7,
    parcels: [
      { id: 108, thumb: null, x: 14, y: -3.4, ownerAddress: null, available: true, sector: 7 },
      { id: 109, thumb: null, x: 16, y: -3.4, ownerAddress: null, available: true, sector: 7 },
      { id: 110, thumb: null, x: 13, y: -1.7, ownerAddress: null, available: true, sector: 7 },
      { id: 111, thumb: null, x: 15, y: -1.7, ownerAddress: null, available: true, sector: 7 },
      { id: 112, thumb: null, x: 17, y: -1.7, ownerAddress: null, available: true, sector: 7 },
      { id: 113, thumb: null, x: 12, y: 0, ownerAddress: null, available: true, sector: 7 },
      { id: 114, thumb: null, x: 14, y: 0, ownerAddress: null, available: true, sector: 7 },
      { id: 115, thumb: null, x: 16, y: 0, ownerAddress: null, available: true, sector: 7 },
      { id: 116, thumb: null, x: 18, y: 0, ownerAddress: null, available: true, sector: 7 },
      { id: 117, thumb: null, x: 13, y: 1.7, ownerAddress: null, available: true, sector: 7 },
      { id: 118, thumb: null, x: 15, y: 1.7, ownerAddress: null, available: true, sector: 7 },
      { id: 119, thumb: null, x: 17, y: 1.7, ownerAddress: null, available: true, sector: 7 },
      { id: 120, thumb: null, x: 14, y: 3.4, ownerAddress: null, available: true, sector: 7 },
      { id: 121, thumb: null, x: 16, y: 3.4, ownerAddress: null, available: true, sector: 7 },
    ],
  },
  {
    sector: 8,
    parcels: [
      { id: 122, thumb: null, x: -14, y: -3.4, ownerAddress: null, available: true, sector: 8 },
      { id: 123, thumb: null, x: -16, y: -3.4, ownerAddress: null, available: true, sector: 8 },
      { id: 124, thumb: null, x: -13, y: -1.7, ownerAddress: null, available: true, sector: 8 },
      { id: 125, thumb: null, x: -15, y: -1.7, ownerAddress: null, available: true, sector: 8 },
      { id: 126, thumb: null, x: -17, y: -1.7, ownerAddress: null, available: true, sector: 8 },
      { id: 127, thumb: null, x: -12, y: 0, ownerAddress: null, available: true, sector: 8 },
      { id: 128, thumb: null, x: -14, y: 0, ownerAddress: null, available: true, sector: 8 },
      { id: 129, thumb: null, x: -16, y: 0, ownerAddress: null, available: true, sector: 8 },
      { id: 130, thumb: null, x: -18, y: 0, ownerAddress: null, available: true, sector: 8 },
      { id: 131, thumb: null, x: -13, y: 1.7, ownerAddress: null, available: true, sector: 8 },
      { id: 132, thumb: null, x: -15, y: 1.7, ownerAddress: null, available: true, sector: 8 },
      { id: 133, thumb: null, x: -17, y: 1.7, ownerAddress: null, available: true, sector: 8 },
      { id: 134, thumb: null, x: -14, y: 3.4, ownerAddress: null, available: true, sector: 8 },
      { id: 135, thumb: null, x: -16, y: 3.4, ownerAddress: null, available: true, sector: 8 },
    ],
  },
]
